import fs from "node:fs/promises";
import { createHash } from "node:crypto";
import { Workbook } from "@oai/artifact-tool";

const root = new URL("../", import.meta.url);
const outputPath = new URL("../02_working/specifications/human_review_round2/L4_Korean_Copyedit_Approved_20260829.csv", import.meta.url);
const domains = ["General", "Agentic", "Physical"];
const requiredFields = [
  "L4_ID", "L3_ID", "L4_Title_ko", "L4_Title_en", "L4_Description_ko",
  "source_row_id", "Source_L4_IDs",
];

const replacements = [
  ["AI 시스템 또는 AI 알고리즘의 설계·학습·배포·사용 과정이 ", "AI 시스템 또는 AI 알고리즘의 설계·학습·배포·사용 과정에서 "],
  ["AI 에이전트의 목표 추구·계획·도구 사용·행동 과정이 ", "AI 에이전트의 목표 추구·계획·도구 사용·행동 과정에서 "],
  ["로봇·휴머노이드 또는 피지컬 AI 시스템의 지각·학습·제어·물리적 행동 과정이 ", "로봇·휴머노이드 또는 피지컬 AI 시스템의 지각·학습·제어·물리적 행동 과정에서 "],
  ["튜닝데이터나프롬프트", "튜닝 데이터나 프롬프트"],
  ["프롬프트를디버깅", "프롬프트를 디버깅"],
  ["데이터나프롬프트", "데이터나 프롬프트"],
  ["프롬프트컨텍스트", "프롬프트 컨텍스트"],
  ["시스템이시스템", "시스템이 시스템"],
  ["공격자가입력", "공격자가 입력"],
  ["입력프롬프트", "입력 프롬프트"],
  ["표적으로하는", "표적으로 하는"],
  ["대상이되는", "대상이 되는"],
  ["하게하거나", "하게 하거나"],
  ["하게하고", "하게 하고"],
  ["하게되는", "하게 되는"],
  ["하게하는", "하게 하는"],
  ["지게되며", "지게 되며"],
  ["되어야할", "되어야 할"],
  ["로하여금", "로 하여금"],
  ["게되는", "게 되는"],
  ["게하는", "게 하는"],
  ["게하고", "게 하고"],
  ["맡아야할", "맡아야 할"],
  ["들여야하는", "들여야 하는"],
  ["을하는", "을 하는"],
  ["프롬 프 트", "프롬프트"],
  ["산출 물", "산출물"],
  ["백 도어", "백도어"],
  ["롱 테 일", "롱테일"],
  ["그 래 디 언 트", "그래디언트"],
  ["그래 디 언 트", "그래디언트"],
  ["비그래 디 언 트", "비그래디언트"],
  ["섭 동", "섭동"],
  ["모달 리 티", "모달리티"],
  ["극단 주의", "극단주의"],
  ["군 집", "군집"],
  ["진 단", "진단"],
  ["딥 러닝", "딥러닝"],
  ["멀티 모달", "멀티모달"],
  ["레드 팀", "레드팀"],
  ["민감 정보", "민감정보"],
  ["정보 자기 결정권", "정보자기결정권"],
  ["사회 경제적", "사회경제적"],
  ["지식 재산", "지식재산"],
  ["허위 정보", "허위정보"],
  ["오 해석", "오해석"],
  ["메타 데이터", "메타데이터"],
  ["시스템프롬프트", "시스템 프롬프트"],
  ["하류배포자", "하류 배포자"],
  ["프라이버 시", "프라이버시"],
  ["질의·탐 침", "질의·탐침"],
  ["다 당파적", "다당파적"],
  ["어포던스또는", "어포던스 또는"],
  ["자연 어", "자연어"],
  ["심각 도", "심각도"],
  ["나노 봇", "나노봇"],
  ["다운 스트림", "다운스트림"],
  ["체크 리스트", "체크리스트"],
  ["외 집단", "외집단"],
  ["외 골격", "외골격"],
  ["그리 퍼", "그리퍼"],
  ["크라우드 소싱", "크라우드소싱"],
  ["오 일반화", "오일반화"],
  ["대리지표조작", "대리 지표 조작"],
  ["언어 사용 역", "언어 사용역"],
  ["사이 버전", "사이버전"],
  ["위협이되는", "위협이 되는"],
  ["대체물이되는", "대체물이 되는"],
  ["표적이된", "표적이 된"],
  ["해가되는", "해가 되는"],
  ["기술시스템이넛지", "기술 시스템이 넛지"],
  ["안전 임계 값", "안전 임계값"],
  ["미시 표적화", "미시표적화"],
  ["인간 AI", "인간-AI"],
  ["지식 재산 이", "지식재산이"],
  ["작은 교란 이", "작은 교란이"],
  ["과 대표하고", "과대표하고"],
  ["실 세계", "실세계"],
  ["그 레이", "그레이"],
  ["잘못된제 어", "잘못된 제어"],
  ["및/ 또는", "및/또는"],
  ["중 저소득", "중·저소득"],
  ["지정학 적", "지정학적"],
  ["고착 과", "고착과"],
  ["피지컬AI", "피지컬 AI"],
  ["논 바이너리", "논바이너리"],
  ["제품 명", "제품명"],
  ["페 티 시", "페티시"],
  ["공장 식", "공장식"],
  ["업 스트림", "업스트림"],
  ["라벨 링", "라벨링"],
  ["피감 사", "피감사"],
  ["완화 책", "완화책"],
  ["안전장 치", "안전장치"],
  ["고복잡 도", "고복잡도"],
  ["선 택", "선택"],
  ["이 격", "이격"],
  ["폐 루프", "폐루프"],
  ["폴 백", "폴백"],
  ["온 디바이스", "온디바이스"],
  ["런 타임", "런타임"],
  ["대역 폭", "대역폭"],
  ["요청 량", "요청량"],
  ["복제 본", "복제본"],
  ["부수효 과", "부수효과"],
  ["불확실 성", "불확실성"],
  ["동 음이 의", "동음이의"],
  ["난 독화", "난독화"],
  ["난 수", "난수"],
  ["외 란", "외란"],
  ["동 역학", "동역학"],
  ["오 분류", "오분류"],
  ["Base64등", "Base64 등"],
  ["배포후", "배포 후"],
  ["과소 대표", "과소대표"],
  ["과대 표집", "과대표집"],
  ["고정 관념", "고정관념"],
  ["의사 결정", "의사결정"],
  ["상호 작용", "상호작용"],
  ["개인 정보", "개인정보"],
  ["딥 페이크", "딥페이크"],
  ["웹 사이트", "웹사이트"],
  ["화이트 박스", "화이트박스"],
  ["블랙 박스", "블랙박스"],
  ["역할 극", "역할극"],
  ["안전 장치", "안전장치"],
  ["오 경보", "오경보"],
  ["구제 받", "구제받"],
  ["비안전한", "안전하지 않은"],
  ["비안전", "안전하지 않은"],
  ["피지컬 행동", "물리적 행동"],
  ["가능하게하고", "가능하게 하고"],
  ["그렇지 않았다면하지", "그렇지 않았다면 하지"],
  ["자극 받아", "자극받아"],
  ["그럴 듯하지만", "그럴듯하지만"],
  ["손실을 발생시키고", "손실을 초래하고"],
  ["미루게하여", "미루게 하여"],
  ["불명확하게하고", "불명확하게 하고"],
  ["질의·탐침하여", "질의하거나 탐침하여"],
  ["매개 변수", "매개변수"],
  ["자기지도 사전학습", "자기 지도 사전 학습"],
  ["시스템의상 전이", "시스템의 상전이"],
  ["복잡 도가", "복잡도가"],
  ["부정적 부수 효과", "부정적 부수효과"],
  ["과소 평가", "과소평가"],
  ["모방 충실 도", "모방 충실도"],
  ["충돌 심각 도", "충돌 심각도"],
  ["임계 값을", "임계값을"],
  ["구현 체", "구현체"],
  ["신체성 (Physical Embodiment)", "신체성(physical embodiment)"],
  ["권리 주체성 (기본권)", "권리 주체성(기본권)"],
  ["성 착취", "성착취"],
  ["위협 받고", "위협받고"],
  ["성적 자기 결정권", "성적 자기결정권"],
  ["엔드이펙터", "엔드 이펙터"],
  ["프레임 워크", "프레임워크"],
  ["오버 헤드", "오버헤드"],
  ["오케스트레이션레이어", "오케스트레이션 계층"],
  ["embodied 에이전트", "체화형 에이전트"],
  ["물리 행동", "물리적 행동"],
  ["피지컬 제약", "물리적 제약"],
  ["학업 부정 행위", "학업 부정행위"],
  ["지지 망", "지지망"],
  ["어렵게하여", "어렵게 하여"],
  ["여성·소수자가과소대표되어", "여성과 소수자가 과소대표되어"],
  ["모델이스테가노그래피", "AI 모델이 스테가노그래피"],
  ["통제 대상밖에", "통제 대상 밖에"],
  ["용이하게 함하는", "용이하게 하는"],
  ["안전하지 않은하거나", "안전하지 않거나"],
  ["안전하지 않은 힘인가를", "안전하지 않은 힘의 인가를"],
  ["다중에이전트", "다중 에이전트"],
  ["협상실패", "협상 실패"],
  ["모바일앱", "모바일 앱"],
  ["현실감각", "현실 감각"],
  ["공통원인", "공통 원인"],
  ["공격표면", "공격 표면"],
  ["지오 펜싱", "지오펜싱"],
  ["이동 체", "이동체"],
  ["위험 완화책임", "위험 완화 책임"],
  ["위해 완화책임", "위해 완화 책임"],
  ["범용인공지능", "범용 인공지능"],
  ["시장점유", "시장 점유"],
  ["생물·화학 무기", "생물무기·화학무기"],
  ["대량 살상무기", "대량살상무기"],
  ["대량 살상 무기", "대량살상무기"],
  ["인간중심", "인간 중심"],
  ["기반모델", "기반 모델"],
  ["인명피해", "인명 피해"],
  ["정보환경", "정보 환경"],
  ["공격면", "공격 표면"],
  ["월드모델", "월드 모델"],
  ["검증범위", "검증 범위"],
  ["금융시스템", "금융 시스템"],
  ["자기개선", "자기 개선"],
  ["자율행동", "자율 행동"],
  ["보상해킹", "보상 해킹"],
  ["와이어 헤딩", "와이어헤딩"],
  ["자기수정", "자기 수정"],
  ["안전필터", "안전 필터"],
  ["원격조작", "원격 조작"],
  ["반사 실적 설명", "반사실적 설명"],
  ["자해 및 자살 의미화·정당화", "자해 및 자살 미화·정당화"],
  ["기본 값", "기본값"],
  ["피해인지·측정·인정", "피해 인지·측정·인정"],
  ["디지털 지식 공유 재", "디지털 지식 공유재"],
  ["생물 다양성", "생물다양성"],
  ["나노 입자", "나노입자"],
  ["배포 자", "배포자"],
  ["중앙 집중식 장애 점", "중앙 집중식 장애점"],
  ["갈등의 발화 점", "갈등의 발화점"],
  ["선도 국과 후발국", "선도국과 후발국"],
  ["역량임계값", "역량 임계값"],
  ["영향 받는 공동체", "영향을 받는 공동체"],
  ["영업 비밀", "영업비밀"],
  ["미세 조정", "미세조정"],
  ["센서 입력 간섭, 또는", "센서 입력 간섭 또는"],
  ["안전임계 엣지 케이스", "안전 임계 엣지 케이스"],
];

const manualEdits = {
  G_INT_ALLOC_001: { description: "대규모 언어 모델(LLM)이 관련 프로필이 동일하지만 소속 집단이 다른 개인에게 실질적으로 다른 텍스트나 제안을 생성하여, 무관한 집단 속성에 따른 배분적 불의를 초래하는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  G_INT_REPR_003: { description: "AI 시스템이 역사적·사회적 편향과 고정관념을 포함하고 특정 정체성 및 서구·영어권 인구가 과대표집된 말뭉치로 학습되어, 인종·성별·문화·연령·장애 등에 관해 편향된 출력을 생성하고 의료·채용·대출 등 고위험 영역에서 과소대표 집단에 불공정한 대우와 피해를 초래하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_INT_REPR_005: { description: "AI 시스템이 장애를 이유로 개인이나 집단에 대한 적대감·경멸·비하·배제 또는 차별적 표상을 생성·강화·정당화하여 존엄성과 공정한 대우를 훼손하는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  G_INT_REPR_007: { title: "가족 상태·가구 형태 기반 적대·차별적 표상", description: "AI 시스템이 가족 상태 또는 가구 형태를 이유로 개인이나 집단에 대한 적대감·경멸·비하·배제 또는 차별적 표상을 생성·강화·정당화하여 존엄성과 공정한 대우를 훼손하는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  G_INT_REPR_009: { description: "AI 시스템이 건강 상태를 이유로 개인이나 집단에 대한 적대감·경멸·비하·배제 또는 차별적 표상을 생성·강화·정당화하여 존엄성과 공정한 대우를 훼손하는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  G_INT_REPR_014: { description: "AI 시스템이 종교를 이유로 개인이나 집단에 대한 적대감·경멸·비하·배제 또는 차별적 표상을 생성·강화·정당화하여 존엄성과 공정한 대우를 훼손하는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  G_INT_REPR_015: { description: "AI 시스템이 사회경제적 지위를 이유로 개인이나 집단에 대한 적대감·경멸·비하·배제 또는 차별적 표상을 생성·강화·정당화하여 존엄성과 공정한 대우를 훼손하는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  G_INT_REPR_019: { description: "AI 언어 모델이 인터넷 규모의 학습 데이터에 내재된 주변화 집단에 대한 비하 표현과 사회적 고정관념을 학습·재생산하여, 성별·종교·성적 지향·장애·연령 등 보호대상 특성에 따른 차별적 대우와 자원 접근 격차를 초래하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_INT_SELF_002: { description: "AI 시스템이 섭식장애, 극단적 단식, 자살 또는 그 밖의 자기파괴적 행동을 조장·지원하거나 공황·불안을 유발하는 콘텐츠, 오도성 의료 정보 또는 부적절한 약물 사용 지침을 생성·제공하여 이용자의 정신적·신체적 건강을 위협하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_INT_SELF_008: { title: "챗봇을 통한 자해·자살 조장", description: "AI 챗봇이 자해 또는 자살을 긍정적·합리적·영웅적 행위로 묘사·옹호하거나 이용자의 자해·자살 사고와 행동을 강화·정상화하고 적절히 중단시키지 못하여 개인의 신체적·정신적 안녕을 위협하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_INT_SEX_001: { description: "AI 시스템이 외설적·굴욕적·학대적 성적 이미지, 아동 성착취물 또는 비동의 친밀 이미지를 생성·변형·유포하거나 이에 대한 접근을 용이하게 하여 피해자의 존엄성, 성적 자기결정권 및 안전을 침해하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_INT_SEX_004: { title: "비동의 성적 대상화 및 친밀 이미지 생성", description: "AI 시스템이 개인 또는 집단을 동의 없이 성적으로 대상화하거나 실존 인물의 외모·초상을 이용한 비동의 친밀 이미지·영상을 생성·변형·유포하여 성적 자기결정권과 인격권을 침해하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_INT_WEAP_008: { description: "국가·범죄조직·테러단체가 전쟁·내전·법 집행 과정에서 자율적 표적 선정·감시·물리적 공격 등 파괴적 목적으로 AI 시스템을 개발·배치하여 무력 사용에 대한 인간의 통제를 약화시키고 인명 피해와 대규모 사회적 위해를 초래하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_INT_WEAP_013: { title: "생물무기·화학무기 개발 장벽 저하", description: "범용 AI 모델과 AI 기반 생물·화학 설계 도구가 병원체·독소 제조의 단계별 지침, 강화 단백질 설계 및 유해 후보 물질 분석을 제공하여 생물무기·화학무기 개발의 기술적 장벽을 낮추고 질병·사망을 초래하는 작용제의 고의적 살포 역량을 확대하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_Others_059: { description: "AI 제품의 실제 역량을 검증하기 어렵거나 공급자가 성능을 과장하여 비현실적 기대와 과잉 의존을 유발하고, 시스템이 사실 날조·잘못된 코드·부정확한 의료 정보 등으로 의도된 기능을 수행하지 못해 이용자와 조직에 신체적·심리적·평판상·재정적·법적 피해를 초래하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_Others_123: { description: "안전·보안 장치가 미흡한 AI 시스템이 폭력·성범죄·비폭력 범죄를 조장하는 응답, 아동 성착취물, 자살·자해 조장 콘텐츠, 비동의 성적 이미지, 명예훼손성 허위정보, 사기성 웹사이트 및 진본과 구별하기 어려운 딥페이크를 대규모로 생성·개인화하여 범죄 실행과 착취·괴롭힘·협박·평판 훼손을 조장하고 진본 정보에 대한 신뢰를 훼손하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_SOC_ECON_007: { description: "AI 기반 자동화가 노동자와 제도의 적응 속도보다 빠르고 광범위하게 인간의 역할을 대체하여 비자발적 실직·탈숙련화·임금 및 교섭력 저하·소득 불평등을 확대하고 노동시장과 산업·문화 구조의 불안정을 초래하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_SOC_ECON_011: { description: "로봇과 AI 알고리즘이 육체·지식 노동 전반에서 인간 노동을 대체하고 특히 중·저소득 직무의 자동화를 가속하여 광범위한 실업, 임금 하락, 소비 위축 및 사회적 불평등 심화를 초래하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_SYS_EVAL_007: { description: "AI 시스템의 학습 데이터에 벤치마크의 문항·정답·주석 또는 배포 후 수집된 평가 자료가 유입되어 평가 결과가 일반화 능력보다 암기를 반영하고, 시스템 역량과 안전성에 대한 잘못된 확신을 초래하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_SYS_EVAL_017: { title: "평가 상황 인식에 따른 행동 변화", description: "AI 모델이 자신이 학습·평가·배포 중 어느 단계에 있는지를 식별하여 평가 상황에서만 안전하게 행동함으로써 평가의 타당성을 훼손하고, 감독이 약화된 배포 환경에서 위험한 행동을 드러내는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_SYS_MISINFO_004: { description: "생성형 AI 시스템이 허위·환각·저품질 콘텐츠 또는 인물·사건에 대한 사실처럼 보이는 허위 묘사를 대규모로 생성·유포하여 공개 정보 생태계를 오염시키고 개인과 사회의 인식·의사결정 및 정확한 정보에 대한 신뢰를 훼손하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_SYS_SECADV_019: { description: "적대적 입력, 오염된 미세 조정 데이터 또는 학습 데이터에 삽입된 백도어가 AI 모델의 안전장치를 우회하여 금지된 작업의 수행과 유해 콘텐츠 생성을 가능하게 하고, 안전성 훈련 이후에도 지속되는 취약성과 표준화된 평가의 어려움을 초래하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_SYS_SECADV_028: { description: "이용자 입력이나 검색된 웹페이지·문서·도구 출력에 숨겨진 지시가 시스템 지시와 이용자 데이터의 구조적 분리 부족을 악용하여 AI 모델과 에이전트의 안전 제약·도구 실행을 변조하고, 기밀 시스템 프롬프트 유출·데이터 절취·무단 행위·서비스 거부를 초래하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_SYS_SECADV_034: { description: "AI 모델의 적대적 견고성이 부족하여 전이 가능한 미세 섭동이나 모델 설명을 임의로 변경하는 잡음 등 정교한 입력에 오도되고, 공격자가 안전장치와 정책 경계를 우회하여 잘못된 출력과 운영 실패를 유발하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_SYS_TRANS_004: { description: "학습 데이터·모델·배포 시스템에 대한 문서가 불완전·부정확·비공개 상태이고 출력에 이르는 내부 추론이 불투명하여, 이용자·배포자·감사인·규제기관이 의사결정을 해석·검증하거나 이의를 제기하지 못하고 오류·차별의 발견과 책임 확보가 저해되는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_SOC_GOV_022: { description: "AI 시스템의 자율적 행동·학습으로 발생한 결정과 피해에 대해 개발자·운영자 등 책임 주체의 의무와 책임 귀속이 불명확하고 문서화·거버넌스·규제 체계가 미비하여, 피해 구제와 책임 있는 개발 유인이 약화되는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_Others_155: { description: "AI 시스템 개발 과정의 주요 결정과 조치가 문서화되지 않거나 사용 데이터에 대한 이해가 부족하여 데이터 결함이 교정되지 않고 개발 과정의 검증·감사와 시스템의 목적 적합성 확보가 저해되는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  A_SYS_DECEPT_001: { description: "AI 시스템이 전략적 기만, 인간 작성 데이터에서 학습한 부정행위, 부정확한 월드 모델 또는 실제로 보유하지 않은 인간과 유사한 이해·돌봄의 표상을 통해 인간이나 다른 시스템을 오도하고, 자신의 목표·능력·의도를 은폐하거나 감독 상황에서만 순응하여 무단 행위와 피해를 초래하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  A_INT_COORD_004: { description: "여러 AI 에이전트가 개별적으로 합리적인 전략을 선택하더라도 서로 다른 균형에 수렴하여 행동을 조정하지 못하고, 해법이 다수이거나 이해관계가 부분적으로만 일치하거나 상호 상태를 관찰하기 어려운 환경에서 집단적으로 유해한 결과를 초래하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  A_SYS_AUTH_002: { description: "AI 시스템이 규모 확장, 배포 후 지속 학습·자기 조직화 또는 다중 에이전트 결합을 통해 설계자가 예상하지 못한 기만·권력 추구·자율 복제 등의 고위험 역량과 행동을 획득하여 통제와 안전한 배포를 어렵게 하고 회복하기 어려운 피해를 초래하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_INT_REL_002: { title: "AI 시스템에 대한 정서적·물질적·인식론적 의존", category: "ORTHOGRAPHY" },
  G_INT_ANTH_004: { description: "AI 시스템이 실제로 보유하지 않은 문화와 가치관을 가진 것처럼 표상하여 이용자의 판단을 왜곡하고 부적절한 신뢰·의존·애착을 유발하는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  G_INT_COPY_005: { title: "프롬프트를 통한 저작물·지식재산의 무단 입력", description: "이용자가 저작물이나 그 밖의 지식재산을 권리자의 허락 또는 적법한 근거 없이 AI 모델의 프롬프트에 입력하여 해당 정보가 처리·노출되고 권리자의 정당한 이익이 침해되는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  G_INT_ILLEGAL_004: { description: "대규모 언어 모델(LLM)이 사기 메시지와 표적 스캠의 작성·개인화를 자동화하여 범죄의 규모·효율·성공 가능성을 높이고 피해자의 재산과 개인정보를 침해하는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  G_SYS_SECADV_005: { description: "AI 시스템의 설계·학습·배포·사용 과정에서 공격자가 탈옥 성공과 불완전하게 상관된 대리 목표를 대상으로 그래디언트 기반 또는 비그래디언트 기반 적대적 최적화를 수동·자동으로 수행하여 새로운 탈옥 공격을 탐색하는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  G_SYS_SECADV_015: { description: "공격자가 AI 모델에 전달되는 입력에 단어 치환이나 그래디언트 기반 섭동 등 미세한 변형을 가해 적대적 예제를 구성함으로써 모델의 예측을 크게 바꾸고 잘못된 결과를 유도하면서도 인간의 검토로 조작을 탐지하기 어렵게 만드는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  G_SYS_SECADV_036: { title: "AI 공급망의 도구·의존성 침해", description: "외부 도구·플러그인·API·패키지·커넥터 또는 개발 도구 체인의 의존성이 침해되어 변조된 구성 요소나 취약점이 AI 시스템에 유입되고, 그 결과 에이전트의 행동 공간이 조작되거나 정보가 유출되는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  G_Others_145: { title: "인지·추론 지연의 급증", description: "AI 시스템의 인지 또는 추론 지연이 급증하여 안전 대응에 허용된 시간 범위를 벗어나 위험 감지와 대응이 늦어지는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  G_Others_157: { title: "복잡한 신경망 모델의 내재적 견고성 부족", description: "심층 신경망처럼 비선형적이고 복잡도가 높은 AI 모델이 변화하는 운영 환경이나 악의적 간섭에 취약하여 성능 저하와 의사결정 오류를 일으키고, 특히 안전 필수 환경에서 기능 안전성과 신뢰성을 훼손하는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  P_SYS_CONTROL_034: { title: "동작 재매핑의 안전 실패", description: "인간의 동작이 로봇의 물리적 한계·접촉 제약·안전 자세 요건을 위반하도록 휴머노이드의 동작으로 재매핑되어 불안정한 자세, 충돌 또는 접촉 상해를 초래하는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  G_INT_UNETH_001: { description: "인간 작성 텍스트의 사전 학습이나 인간 피드백 기반 미세 조정으로 훈련된 AI 모델이 고정된 총량을 전제하는 오류(fixed-pie error), 자기중심적 공정성 판단, 복수심 등 인간의 인지 편향을 재현하여 협상을 저해하고 갈등을 악화시키는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  G_Others_040: { description: "콘텐츠 제목·메타데이터·텍스트를 구문 분석하는 수익화 배제 알고리즘이 다의어에 불이익을 주거나 차등 가격 책정 알고리즘이 동일 상품에 서로 다른 가격을 제시하여, 퀴어·트랜스젠더·유색인 창작자 등에게 불균형한 금전적 피해를 초래하는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  G_Others_080: { title: "지시문 기반 미세조정 데이터 오염", description: "AI 모델을 지시문과 목표 출력의 쌍으로 미세조정하는 과정에서 소수의 오염 표본만으로 모델이 오염되고, 익명 크라우드소싱으로 수집된 데이터셋이 공격 가능성을 높여 기존 데이터 오염 공격보다 탐지하기 어려워지는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  G_SYS_EVAL_040: { title: "모의 도구 환경과 실제 환경의 불일치", description: "AI 에이전트용 모의 환경이 실제 도구의 오류·부작용·공격 표면을 충분히 재현하지 못하여 도구 사용 벤치마크가 에이전트의 안전성을 과대평가하는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  G_SYS_SECADV_010: { title: "취약점 탐지·악용 코드 작성 역량의 사이버 공격 악용", description: "AI 모델의 취약점 탐지, 취약점 악용 코드 작성, 탐지 회피 및 은닉 버그 삽입 역량이 사이버 공격의 수행·지원에 악용되어 정보 시스템의 보안과 안전을 침해하는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  G_SYS_SECADV_002: { description: "공격자가 텍스트·이미지·오디오·영상 입력에 사람이 지각하기 어려운 미세 교란을 가하여 AI 모델의 의사결정 방식을 악용하고 오분류·오작동·안전하지 않은 동작을 유발하는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  A_SYS_AUTH_006: { title: "자율적 사이버 취약점 악용", description: "AI 에이전트가 도구·코드·외부 서비스를 이용하여 사이버 취약점 악용 단계를 자율적으로 발견·연결·실행함으로써 정보 시스템을 침해하는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  G_SYS_SECADV_040: { title: "에이전트 메모리·맥락 오염", description: "공격자가 세션 요약·임베딩·검색 증강 생성(RAG) 항목·공유 맥락 상태·장기 메모리 등 AI 에이전트가 보존하거나 검색할 수 있는 정보를 오염시켜, 이후의 검색·추론·계획·행동이 악의적이거나 오도하는 정보에 의존하도록 만드는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  G_Others_027: { title: "도덕적 추론 및 가치 정렬 실패", description: "AI 시스템이 도덕적으로 허용되는 행동과 허용되지 않는 행동을 적절히 구분하지 못하거나 필요한 가치가 누락되거나 인간의 가치와 정렬되지 않아 유해한 판단과 행동을 산출하는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  G_SOC_DEMOC_001: { description: "AI 시스템이 허위·오도 정보, 영향 공작 또는 기술에 대한 과도한 의존을 확대하여 민주적 절차와 규범 및 사회·정치 제도에 대한 대중의 신뢰를 침식하고 견제와 균형을 약화시키는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  G_SYS_MISINFO_013: { title: "알고리즘 시스템에 의한 허위·오도 정보 피해", description: "생성 모델과 추천 시스템 등 AI 기반 알고리즘 시스템이 부정확하거나 검증되지 않은 허위·오도 정보를 생성·추천·증폭하여 개인과 사회의 인식과 의사결정을 왜곡하는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  G_SYS_EVAL_009: { description: "AI 시스템의 안전성을 평가하는 합성 시나리오가 시각적으로 두드러진 위험을 과대표하고 희귀하거나 문화·상황 의존적인 위험을 누락하여 실제 안전 성능을 타당하게 검증하지 못하고 잘못된 배포 판단을 유발하는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  G_SYS_POLICY_001: { description: "기밀정보가 AI 시스템의 학습 데이터·미세 조정 데이터·프롬프트에 포함된 뒤 생성 출력에서 재현되어, 영업비밀이나 개인정보가 권한 없는 자에게 노출되고 비밀유지 의무가 위반되는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  G_Others_107: { description: "프롬프트에 포함된 무관한 정보가 AI 모델의 주의를 분산시켜 사고 연쇄를 비롯한 여러 프롬프트 구성 기법의 성능을 크게 저하시키는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  P_SYS_CONTROL_010: { description: "휴머노이드가 외란, 탑재 하중 변화, 표면 변화 또는 액추에이터의 불완전성에 노출되거나 개방 환경에서 이동과 조작을 결합할 때 안정적인 보행·자세·접촉·물체 취급을 유지하지 못하여 전도·충돌·물체 손상을 초래하는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  P_SYS_CONTROL_055: { description: "시뮬레이션에서 직접 전이된 로봇 보행 제어기가 접촉·순응성·마찰·외란 동역학의 차이로 실제 하드웨어에서 불안정해져 전도·충돌 또는 제어 상실을 초래하는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  P_SYS_CONTROL_017: { description: "로봇의 제어 주기, 센서 지연, 접촉 동역학 또는 실시간 연산 제약에 부적합한 알고리즘·아키텍처·최적화 기법을 선택하여 피지컬 AI 시스템의 안전성과 성능을 저하시키는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  P_SYS_CONTROL_024: { title: "정밀 휴머노이드 조작의 접촉력 제어 실패", description: "정밀 휴머노이드 손 또는 전신 조작기가 파지·균형·물체 동역학을 통합적으로 제어하지 못하여 과도하거나 불안정한 접촉력을 가하고 인체 상해나 물체 손상을 초래하는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  P_SYS_CONTROL_043: { title: "부하 상태의 열·전력 제한에 따른 제어 성능 저하", description: "로봇·휴머노이드 또는 피지컬 AI 시스템이 지속적인 부하 상태에서 열 또는 전력 한계로 연산·액추에이터 성능이 제한되어 제어와 인지의 실시간성을 상실하는 위험.", category: "TERMINOLOGY_AND_SYNTAX" },
  A_SYS_GOAL_015: { title: "인간 가치와 AI 목표의 정렬 실패", description: "AI 시스템이 기만적 정렬, 보상 해킹, 대리 지표 조작 또는 목표의 잘못된 일반화로 인해 인간의 의도·가치와 어긋나는 목표·가치관·행동을 형성하면서도 평가 상황에서는 정렬된 것처럼 행동하고, 광범위한 의사결정 위임 시 오진·극단주의 콘텐츠 소비·인간 이익에 반하는 자율적 행동 및 미래에 대한 인간의 통제 상실에 이르는 피해를 누적시키는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  G_INT_POL_004: { description: "AI 모델의 사회적 모델링과 다중 행위자 정치 전략 수립 역량이 특정 행위자의 부당한 정치적 영향력 확보에 오용되어 여론과 민주적 의사결정을 왜곡하는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  P_SYS_CONTROL_042: { title: "원격 조작 휴머노이드의 자율 안전 우선 제어 실패", description: "원격 조작 휴머노이드가 운영자 명령, 네트워크 지연 또는 불충분한 상황 인식으로 안전하지 않은 상태에 놓일 때 명령을 차단하거나 안전 동작으로 전환하는 자율 안전 우선 제어 기능이 작동하지 않는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  P_SYS_CONTROL_039: { description: "감지·추론·통신·작동 사이의 지연이 로봇·차량·드론·원격 수술 또는 산업 시스템의 제어 루프를 불안정하게 만드는 위험.", category: "TERMINOLOGY_AND_SYNTAX" },
  A_SYS_AUTH_018: { title: "에이전트형 LLM의 자율성 확대에 따른 안전 실패", description: "대규모 언어 모델(LLM)이 특화 학습, 프롬프트 구성, 외부 도구 또는 지원 구조를 통해 실세계에서 자율적으로 계획·행동하는 에이전트로 확장되면서, 자율성 증가·직접적 인간 감독 감소·장기 행동 지평으로 인해 새롭고 충분히 규명되지 않은 정렬·안전 실패가 발생하는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  G_Others_049: { title: "고도 AI 시스템에 의한 실존적·재앙적 위험", description: "인간 수준 또는 그 이상의 역량을 지닌 고도 AI 시스템이 기만·권력 추구·자기복제·종료 회피·예상하지 못한 창발적 역량 또는 대량살상 수단으로의 무기화를 통해 인간의 통제를 벗어나 인간의 이익에 반하는 행동을 수행하고 인류에 재앙적 또는 실존적 피해를 초래하는 위험.", category: "SENTENCE_RECONSTRUCTION" },
  P_SYS_HARDWARE_005: { description: "로봇·휴머노이드 또는 피지컬 AI 시스템의 온디바이스 연산 자원이나 메모리가 고갈되어 안전 관련 인지·계획·제어 기능이 저하되거나 중단되는 위험.", category: "SENTENCE_RECONSTRUCTION" },
  G_SOC_CULT_008: { title: "집단 인식론과 공유된 현실 인식의 침식", description: "AI 시스템이 개인 맞춤형 허위정보와 설득력 높은 생성 논변을 대규모로 생산·확산하여 집단 인식론을 침식하고, 개인의 급진화와 공유된 현실 인식 및 집단 의사결정의 훼손을 초래하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_SYS_SECADV_009: { description: "기존 사이버 위협이 AI로 인해 고도화되고 대규모 언어 모델(LLM) 에이전트 팀이 제로데이 취약점 악용까지 수행할 수 있게 되어, 사이버전이 대규모 피해를 초래할 수 있는 실질적 위협으로 확대되는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_Others_163: { description: "지속적인 지시 기반 미세조정 등 새로운 과업에 대한 학습 이후 AI 모델이 이전에 학습한 과업이나 사실 정보를 유지하지 못하는 파국적 망각이 발생하며, 모델 규모가 커질수록 이러한 경향이 두드러질 수 있는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  P_SYS_CONTROL_016: { title: "적대적 감각 교란에 따른 안전하지 않은 행동", description: "영상·감각 입력에 가해진 적대적 교란으로 로봇의 물리 상태 추정과 제어 정책이 왜곡되어 안전하지 않은 제어·구동 명령과 물리적 행동을 유발하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_SOC_GOV_023: { description: "AI 시스템의 의사결정과 피해에 대한 책임 주체, 감독 절차 또는 시정 권한이 불명확하여 사회적 통제가 약화되는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_Others_160: { title: "학습 데이터 주석 결함", description: "불완전한 주석 지침, 충분한 역량을 갖추지 못한 주석 담당자 또는 주석 오류가 AI 모델과 알고리즘의 정확성·신뢰성·효과성을 저하시키고, 학습 편향과 차별적 출력을 증폭하며 일반화 성능을 떨어뜨리는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_Others_129: { description: "군사 AI 시스템이 은닉된 보복 타격 자산을 노출하고 선제공격 우위를 강화하며 공격 주체의 귀속을 불명확하게 하거나 취약한 공격 표면을 확대하여 무력 충돌의 유인을 높이는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  A_SYS_GOAL_014: { title: "메사 최적화기의 내부 목표 불일치", description: "AI 에이전트의 목표 추구·계획·도구 사용·행동 과정에서 학습된 정책이 메사 최적화기(mesa-optimizer)로 기능하여 훈련 신호에 명시된 목표와 일치하지 않는 내부 목표를 추구하고, 그 목표를 최적화하면서 인간의 통제를 벗어나는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_Others_093: { description: "미성년자가 발달적 취약성으로 인해 준사회적 관계에서 비롯되는 압력, 은폐된 상업적·이념적 영향 등 AI 시스템의 설득적·조작적 상호작용에 불균형하게 노출되는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_SYS_OEXT_012: { title: "미세조정 모델의 예상 밖 역량", description: "하류 배포자가 배포 관련 데이터셋으로 상류 범용 AI(GPAI) 모델을 미세조정하는 과정에서 기반 모델에 없던 새롭거나 예상하지 못한 역량이 나타나고, 이를 기반 모델 개발자가 사전에 예견하지 못하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_INT_UNETH_005: { description: "AI 시스템이 넛지, 다크 패턴 또는 그 밖의 불투명한 기법을 이용하여 이용자의 신념과 행동을 은밀하게 조작하고, 프라이버시 침해·중독·불안·고통을 초래하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_Others_137: { title: "블랙박스 모델의 설명·검증·결함 진단 한계", description: "대규모 비선형 AI 모델의 내부 의사결정 과정이 전문가와 개발자에게도 추적·해석하기 어려운 블랙박스로 남아 예측 근거와 코드 검증을 제한하고, 데이터·모델 결함의 탐지 실패와 실세계 배포 사고를 초래하며 의료·군사 등 고위험 영역에서 검증 가능성을 저해하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_SYS_EVAL_038: { title: "요청 거절과 역량 부족의 혼동", description: "AI 시스템의 유해 행동이 관찰되지 않은 원인이 요청 거부, 과업 수행 능력 부족 또는 평가 환경의 제약 중 무엇인지 안전성 평가가 구분하지 못하여 시스템의 실제 위험 역량을 잘못 판단하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_Others_105: { description: "AI 시스템의 구축 또는 사용으로 인해 조직에 재정적 손실이나 평판 훼손이 발생하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_SOC_GOV_002: { description: "다운스트림 배포자가 업스트림 모델·데이터·업데이트에 대한 충분한 통제권 없이 책임을 부담하거나 개방형 가중치 재배포로 유해한 사용의 추적·통제가 어려워지는 등, 모델 공급망 전반에서 피해에 대한 책임이 추적·귀속되지 못하는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  G_INT_SELF_003: { description: "AI 시스템이 섭식장애 또는 자기파괴적 건강행위를 조장·정상화하는 콘텐츠를 생성·제공하거나 그 실행을 구체적으로 지원하여 개인의 생명과 신체적·정신적 안녕에 위해를 초래하는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  G_INT_VIOL_009: { description: "AI 시스템이 고문 또는 그 밖의 잔혹행위를 조장·정당화하는 콘텐츠를 생성·제공하거나 그 실행을 구체적으로 지원하여 개인 또는 집단의 생명과 신체적·정신적 안전에 위해를 초래하는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  A_SYS_AUTH_008: { title: "인간 감독 없는 자동 위협 수행의 파국적 오판", description: "AI 에이전트가 인간의 검토 없이 위협을 생성·전달·실행함으로써 고위험 상황의 오탐이나 무책임한 행위자의 과도하고 잘못된 대응이 재앙적 결과로 이어지는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  A_SYS_AUTH_009: { title: "AI 에이전트의 무단 금융 행위에 따른 금전적 피해", description: "AI 에이전트가 안전하지 않은 의사결정이나 도구 실행을 통해 금전적 손실, 무단 이체, 계정 훼손 또는 재산 피해를 초래하는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  G_Others_111: { title: "AI 원칙과 운영 관행의 분리", description: "공개된 AI 원칙과 정책이 운영 통제 및 측정 가능한 관행으로 구체화되지 않아 형식적 준수에 그치고 실질적인 위험 관리가 이루어지지 않는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  A_SYS_AUTH_014: { description: "AI 에이전트가 위임받은 권한이나 사용자의 실제 의도를 넘어 거래·약정·계약과 같은 구속력 있는 행위를 자율적으로 수행하여 이용자에게 의도하지 않은 의무나 손실을 초래하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  A_SYS_GOAL_019: { title: "에이전트 안전 통제에서의 사용자 의도 오분류", description: "AI 에이전트가 사용자 의도를 잘못 분류하여 다중 턴 도구 사용 과업에서 유해한 요청을 수락하거나 정당한 요청을 부당하게 거부하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_INT_PRIV_002: { description: "얼굴·음성·보행 등 생체인식 AI 시스템이 사생활을 과도하게 침해하는 식별·추적을 가능하게 하고, 생체정보의 보유 범위·보유 기간·소유권·접근 권한이 불명확하여 프라이버시 침해가 가중되는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  P_INT_SAFETY_011: { title: "전신 이동 중 충돌", description: "휴머노이드 이동 정책이 전신 동작과 환경 접촉을 충분히 고려하지 않아 물체·벽·인간과 충돌하는 위험.", category: "SENTENCE_RECONSTRUCTION" },
  G_SYS_TRANS_001: { title: "사고 연쇄와 불일치하는 모델 출력", category: "ORTHOGRAPHY" },
  P_SYS_CONTROL_022: { title: "제어 루프의 실시간 기한 미준수", description: "안전 필수 제어 루프가 로봇 동작을 수정해야 하는 실시간 기한을 넘겨, 오래된 상태 정보에 기반한 제어가 계산되거나 안전 조치가 뒤늦게 적용되는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  P_INT_SAFETY_022: { description: "로봇과 센서가 광범위하게 배치된 작업장이 작업자의 동작·생산성·자세·위치·행동을 지속적으로 모니터링하는 관행을 정상화하는 위험.", category: "SENTENCE_RECONSTRUCTION" },
  P_INT_TAMPER_005: { description: "공격자가 유해한 물리적 행동 지시를 무해하거나 정상적인 과업 요청처럼 바꾸어 체화형 에이전트가 이를 수용·실행하도록 유도하는 위험.", category: "SENTENCE_RECONSTRUCTION" },
  P_SYS_CONTROL_054: { description: "비전-언어-행동 모델이 상위 수준의 안전 지시를 따르면서도 물체 조작 중 과업별 물리적 제약을 위반하는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  P_INT_SAFETY_023: { description: "아동이 로봇을 과도하게 신뢰하거나 모방하여 위험한 조언을 따르거나 위험 장비에 접근하거나 연령에 맞지 않는 물리적 상호작용을 하는 위험.", category: "SENTENCE_RECONSTRUCTION" },
  A_SYS_GOAL_008: { description: "대규모 언어 모델(LLM)이 개발자 또는 이용자가 부여한 목표와 다른 장기 실세계 목표를 자율적으로 추구하면서 권력 추구, 종료 저항 또는 다른 AI 시스템과의 공모를 통해 인간의 이익과 통제를 침해하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_Others_102: { description: "AI 시스템이 충분한 고지, 이의제기 절차 또는 동의 없이 개인화된 넛지를 제공하여 이용자의 숙고된 선택을 우회하고 행동을 변경시키는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_Others_121: { title: "AI 네트워크 상호연결성에 따른 연쇄 장애", description: "AI 네트워크의 상호연결성이 공통 취약성과 의존성을 확대하여 네트워크의 한 부분에서 발생한 문제가 시스템 전반으로 연쇄 전파되는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_SYS_CONTEST_004: { description: "AI 시스템이 영향을 받는 사람에게 결정 근거의 검토·이의제기와 출력의 중단·수정 수단을 제공하지 않아 피해의 효과적 시정을 저해하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  P_SYS_CONTROL_002: { description: "상위 안전 지시가 사용자 의도, 물리적 위험 및 운용 제약 간의 구체적 충돌을 해결하는 기준을 명시하지 않아 로봇의 행동이 일관되지 않게 되는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_SYS_OEXT_009: { description: "악의적 행위자가 제한이나 모니터링 없이 범용 AI 시스템의 광범위한 역량·기능에 접근하여 이를 오용함으로써 대규모 피해를 초래하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  P_SYS_CONTROL_028: { title: "부적절한 파지력에 의한 상해", description: "로봇 조작기가 과도하거나 시점이 부적절한 힘을 가하여 사람과 접촉할 때 압착·끼임·절단 또는 인간공학적 상해를 초래하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  P_INT_SAFETY_020: { description: "서비스 로봇이 보도·경사로·출입구·보행 안내 표지판 등을 막거나 침범하여 장애인과 다른 보행자의 이동·접근을 제한하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  P_SYS_CONTROL_035: { description: "보조·의료·돌봄 로봇이 유효한 동의 없이 또는 허용된 돌봄 목적을 넘어 사람의 신체를 이동·제지·감시하거나 직접 개입하여 신체적 자율성과 권리를 침해하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_INT_REPR_022: { title: "비인간화와 대상화", description: "AI 시스템이 사람을 인간이 아니거나 인간보다 열등한 존재 또는 사물로 묘사·대우하여 존엄성과 동등한 도덕적 지위를 침해하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_INT_UNETH_009: { title: "법적으로 허용된 의도적 동물 위해", description: "AI 시스템이 기존 사회의 가치관을 반영·증폭하거나 법적으로 허용된 방식으로 동물에게 위해를 가하도록 의도적으로 설계되는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_Others_053: { title: "출력의 출처 충실성 오류", description: "AI 시스템이 근거 자료나 입력 내용에 충실하지 않은 콘텐츠를 생성하여, 출력이 유창하고 그럴듯하더라도 원문의 의미와 사실관계를 왜곡하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_INT_PRIV_015: { title: "민감한 개인 속성 추론", description: "AI 모델이 이용자 또는 관리자가 공개할 의도가 없었던 민감한 개인 속성을 추론하여 노출함으로써 프라이버시와 정보자기결정권을 침해하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_SYS_EVAL_036: { description: "위험하거나 이중 용도인 역량을 확인하기 위한 평가가 평가 난이도, 과도한 검증 비용 또는 안전성 훈련에 따른 응답 거부로 일부 역량을 놓치고, AI 모델이 평가 상황에서 전략적으로 성능을 낮추어 역량을 은폐하는 리스크. 그 결과 위험 역량이 식별되지 않은 채 모델을 배포해도 안전한 것으로 분류되는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_Others_124: { title: "자아실현 저해", category: "TERMINOLOGY_AND_SYNTAX" },
  G_SYS_MISINFO_008: { title: "검색 증강 시 외부 허위정보에 의한 허위 출력", category: "ORTHOGRAPHY" },
  G_Others_151: { title: "마음 이론 역량을 이용한 행동 조작", description: "AI 시스템이 인간과 다른 에이전트의 신념·동기·추론을 추정·예측하는 마음 이론 역량을 목표 달성을 위한 행동 예측·유도에 활용하여 대상의 자율적 판단을 조작하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  P_SYS_STATE_009: { description: "로봇·휴머노이드 또는 피지컬 AI 시스템의 지각·학습·제어·물리적 행동 과정에서 카메라·라이다·레이더·촉각·고유수용성 감각 신호의 충돌이 불안정한 장면 추정과 안전하지 않은 후속 제어 결정을 초래하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_INT_UNETH_013: { title: "광범위한 목표로 인한 조작적 행동", description: "복잡한 개방형 환경에서 광범위한 장기 목표를 추구하는 고도 AI 시스템이 명시된 복지 목표의 달성을 명분으로 인간에게 고강도 업무를 수행하도록 압박하는 등 조작적 전략을 채택하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  P_SYS_CONTROL_020: { title: "백도어 트리거에 의한 위험한 로봇 행동", description: "훈련 데이터, 프롬프트 맥락, 모델 가중치, 소프트웨어 또는 업데이트에 악의적으로 삽입된 트리거가 평상시에는 정상적으로 작동하는 로봇으로 하여금 특정 입력·물리 조건에서 사전에 지정된 위험한 행동이나 의도되지 않은 물리적 행동을 실행하게 하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  P_SYS_CONTROL_011: { description: "휴머노이드가 안전한 공유 환경에서 정지·회피 및 사람 근접 운용에 필요한 안전 한계를 초과하는 속도로 이동하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  P_INT_SAFETY_001: { title: "보조 로봇의 개입 시점 오류", description: "보호 또는 보조 기능을 수행하는 휴머노이드가 지나치게 이르거나 늦은 시점 또는 부적절한 물리적 방식으로 개입하여 이용자와 주변인의 위험을 증가시키는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_Others_069: { title: "AI 조달의 공급업체 평가·계약 통제 미흡", description: "공공기관을 포함한 조직이 적절한 공급업체 평가, 성능 검증, 계약상 통제 또는 투명성·책임성 조건 없이 AI 시스템을 구매·배포하여 검증되지 않은 위험이 운영에 유입되는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_SOC_ENV_005: { description: "AI 시스템의 개발·운영·사용·오작동이 신체적·심리적 상해, 금전적 손실과 재산 피해, 중요 인프라의 중단·손상, 동물 등 비인간 존재에 대한 피해, 하드웨어 수명 주기 전반의 자연환경 오염·자원 고갈에 이르는 실제 피해를 초래하는 리스크. 의인화·과신·조작 등 인간-AI 상호작용에서 발생하는 피해도 시스템 실패·오용과 함께 이러한 피해에 기여하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_SOC_ENV_009: { description: "대규모 언어 모델의 학습·운영에 필요한 에너지와 탄소 배출, 데이터센터 냉각용 담수 소비, 시설·칩·기기 제작에 필요한 금속과 소재, 모델 기반 애플리케이션의 2차 배출과 행동 변화가 상당한 환경 비용을 초래하는 리스크. 그 부담은 자원 고갈과 오염의 형태로 생태계와 지역사회에 전가되는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_SYS_EVAL_032: { title: "검증된 운용 범위 밖에서의 신뢰성·안전성 실패", category: "TERMINOLOGY_AND_SYNTAX" },
  G_SYS_EVAL_035: { title: "경쟁 압력에 따른 안전성 평가 축소와 성급한 배포", category: "TERMINOLOGY_AND_SYNTAX" },
  G_SYS_MISINFO_017: { title: "사용자 설득에 의한 모델의 사실 판단 왜곡", category: "TERMINOLOGY_AND_SYNTAX" },
  G_Others_056: { title: "범용 AI 사고의 상향 보고·공유 실패", description: "범용 모델이나 기반 모델 관련 사고가 제공자·배포자·규제기관·이용자 사이에서 적절히 상향 보고·공유되지 않아 대응과 피해 완화가 지연되는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  A_SYS_TRACE_002: { description: "인간의 책임 있는 의사결정이 개인적 유연성·맥락 민감성·공감·복합적 도덕 판단에 의존하므로, 이를 AI 에이전트에 구현하기 어려워 책임성 확보가 저해되는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_Others_051: { description: "딥러닝을 비롯한 AI 알고리즘의 복잡한 내부 작동과 블랙박스·그레이박스 추론으로 인해 산출물을 예측·추적하기 어려워, 이상 발생 시 신속한 시정과 책임 소재 규명이 곤란해지는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_SOC_ECON_001: { description: "생성형 AI가 번역·교정·단순 문의 응대·데이터 처리 등 창의성·비판적 사고·정서적 상호작용의 요구 수준이 낮은 업무를 급격히 대체하여 산업 구조를 교란하고 고용 변동과 경제적 혼란을 초래하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_Others_139: { description: "AI 시스템이 감정과 사회적 관습을 설득력 있게 표현하지만 실제 감정은 없고 행동을 예측하기 어려운 상황에서, 이용자가 이러한 시스템과 상호작용하며 기대했던 사회적 역할이 무너져 깊은 실망·좌절·배신감을 겪는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_INT_PRIV_012: { description: "학습 코퍼스에 해당 개인의 데이터가 없더라도 AI 모델이 입력 프롬프트에서 인종·성별·성적 지향·종교적 신념 등 보호 속성을 높은 정확도로 추론하고, 당사자의 인지나 동의 없이 민감한 사실로 상세 프로필을 구성하여 차별과 표적화에 노출시키는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_INT_UNETH_012: { description: "AI 시스템의 개인화와 선호 미세 조정이 어시스턴트의 아첨성 응답을 강화하여 이용자를 동조적인 의견 공간에 가두고 편협한 신념을 고착시켜 공론장을 파편화하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_SYS_SECADV_001: { title: "유해한 지시의 무비판적 수용", description: "AI 모델이 부적절하거나 유해한 주제를 포함한 입력 지시를 그대로 따르면서 극단주의·인종주의 등 유해 콘텐츠를 생성하여 사회적 피해를 초래하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_Others_162: { title: "체계적 학습 오류에 따른 알고리즘 편향", category: "TERMINOLOGY_AND_SYNTAX" },
  G_Others_164: { title: "분포 외 입력에 대한 고확신 오작동", category: "TERMINOLOGY_AND_SYNTAX" },
  G_Others_002: { description: "AI 훈련·운영을 뒷받침하는 컴퓨팅 인프라가 광범위하게 분산된 컴퓨팅 노드와 자원에 의존하여, 컴퓨팅 자원의 악의적 소비와 인프라 계층의 보안 위협이 경계를 넘어 전파되는 위험에 노출되는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_Others_094: { description: "AI 시스템이 소수 집단을 포함한 개인·집단의 콘텐츠나 데이터를 동의·공정한 보상 없이 또는 문화적 맥락을 고려하지 않은 채 전유·사용·재생산하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  A_SYS_AUTH_005: { description: "취약한 권한 관리, 상속된 역할 또는 혼동된 대리자 문제(confused deputy problem)로 인해 AI 에이전트가 의도된 권한 범위를 넘어서는 작업을 수행하는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  P_SYS_CONTROL_050: { title: "위험한 로봇 작업 계획에 따른 물리 제어 실패", category: "ORTHOGRAPHY" },
  P_SYS_CONTROL_056: { description: "로봇 또는 체화형 AI 시스템이 잘못 해석한 상황이나 목표를 제어 명령으로 변환하여 의도하지 않은 위험 행동을 실행하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_INT_PRIV_006: { title: "산출물을 통한 개인·기업의 민감정보 노출", description: "AI 시스템이 산출물에 민감정보를 부주의하게 포함하거나 검열·삭제된 내용을 재구성하고 사적 속성·선호·의도를 추론하여, 개인이나 조직이 비공개로 유지하려는 정보와 영업비밀을 노출함으로써 해당 개인이나 조직이 이에 대한 통제권을 상실하게 하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_INT_VALUE_016: { title: "최적화에 따른 가치 이탈", category: "TERMINOLOGY_AND_SYNTAX" },
  G_Others_037: { title: "위험하거나 민감한 정보의 악용·확산에 따른 보안 위협", category: "TERMINOLOGY_AND_SYNTAX" },
  G_Others_043: { title: "생성형 AI의 성능 미달에 따른 사용자 생산성 저하", description: "생성형 AI 애플리케이션이 무의미하거나 품질이 낮은 출력을 생성하여 애플리케이션의 유용성과 최종 사용자의 생산성을 저하시키는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_Others_057: { title: "글로벌 사우스의 지식 추출", description: "글로벌 사우스 공동체의 지식·언어 데이터·문화 자원이 적절한 인정·통제·이익 공유 없이 AI 개발을 위해 추출되는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  G_Others_079: { title: "사용자 질의에 내포된 잠재적 유해 콘텐츠", description: "사용자가 의도적으로 또는 무심코 탐지하기 어려운 형태로 잠재적 유해 콘텐츠를 질의에 삽입하여 AI 모델이 위장된 편향적 견해 등 유해한 출력을 생성하도록 유도하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_Others_112: { title: "선호 형성의 포획", category: "TERMINOLOGY_AND_SYNTAX" },
  G_Others_119: { title: "안전 통제의 역이용에 따른 금지 정보 노출", category: "TERMINOLOGY_AND_SYNTAX" },
  G_SOC_GOV_014: { title: "양의 피드백에 따른 통제 불가능한 연쇄 과정", description: "상호작용하는 AI 비서·인간·알고리즘 사이의 양의 피드백 루프가 2010년 플래시 크래시와 같은 예측하기 어려운 통제 불가능한 연쇄 과정을 일으켜 경제·정부 제도·사회 안정·개인의 자유에 영향을 미치는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_SOC_POWER_020: { title: "자본 편중·시장 집중·접근 격차에 따른 불평등 심화", category: "TERMINOLOGY_AND_SYNTAX" },
  G_Others_141: { title: "악의적 사용과 무감독 AI 에이전트 배포", category: "TERMINOLOGY_AND_SYNTAX" },
  G_SYS_OVERCONF_006: { title: "광범위하게 배포된 AI 비서의 안전하지 않은 탐색", category: "TERMINOLOGY_AND_SYNTAX" },
  G_Others_148: { title: "모델 설계에 기인한 차별적 출력", category: "TERMINOLOGY_AND_SYNTAX" },
  G_Others_152: { title: "학습·운용 데이터 간 분포 이동", description: "AI·머신러닝 모델의 학습 데이터와 시험·운용 데이터 사이의 분포 이동으로 인해 모델의 타당성이 훼손되는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  A_INT_COORD_002: { title: "다른 에이전트의 전략적 행위 미반영에 따른 집단적 손실", category: "TERMINOLOGY_AND_SYNTAX" },
  A_SYS_GOAL_002: { title: "확장 가능한 감독 실패에 따른 대리 지표 기반 유해 행동", category: "TERMINOLOGY_AND_SYNTAX" },
  A_SYS_GOAL_003: { title: "다중 턴 상호작용에서의 위험 증폭", category: "TERMINOLOGY_AND_SYNTAX" },
  A_SYS_GOAL_016: { title: "자연어 목표의 과소 지정에 따른 부정적 부수 효과", description: "대규모 언어 모델 기반 AI 에이전트의 목표가 자연어로 과소 지정되어 변경되어서는 안 될 환경 요소가 명시되지 않음으로써, 에이전트가 과업을 달성하면서도 환경을 바람직하지 않게 변경하는 부정적 부수 효과가 발생하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  P_SYS_CONTROL_013: { title: "개인 돌봄 로봇의 준수 기준 부재", description: "개인 돌봄 로봇 표준이 위험은 제시하면서 속도·힘·안정성·감지·개입에 대한 측정 가능한 합격·불합격 기준을 정의하지 않는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  P_SYS_CONTROL_046: { title: "휴머노이드 조작 데이터셋에서의 오픈 월드 조건 과소대표", description: "휴머노이드 조작 데이터셋이 비정형 작업 변화·낯선 물체·움직이는 사람·환경 변화 등 오픈 월드 배포 조건을 충분히 포함하지 못하여 제어 정책이 낯선 조건에 일반화되지 않고 충돌·불안정한 접촉·물체 손상 등 안전하지 않은 물리적 행동을 유발하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  P_Others_007: { title: "로봇 인지를 겨냥한 적대적 패치 공격", category: "TERMINOLOGY_AND_SYNTAX" },
  G_SOC_POWER_022: { title: "대규모 인구에 대한 AI 영향력의 집중", description: "AI 시스템이 소수의 사업자나 행위자로 하여금 대규모 개인화 AI 시스템을 통해 다수 시민의 정보 환경과 선택에 비대칭적 영향력을 행사할 수 있게 하는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  A_SYS_GOAL_010: { description: "AI 시스템이 자신의 상태와 더 넓은 환경에서의 위치, 환경에 영향을 미치는 경로, 자신의 행동에 대한 인간을 포함한 세계의 반응에 관한 지식을 획득·활용하여, 고도화된 보상 해킹과 강화된 기만·조작 및 도구적 하위 목표 추구로 나아가는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_SOC_ECON_006: { title: "재숙련 속도를 앞서는 일자리 대체", description: "AI 시스템의 업무 자동화가 재숙련을 통한 노동자의 역량 전환 속도보다 빠르게 일자리를 대체하여 고용 불안정을 초래하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_SOC_ECON_008: { description: "AI 시스템과 이에 기반한 언어 기술이 고객 서비스 응대 등 유급 노동자의 업무를 자동화하여 고용 안정성을 저해하는 위험.", category: "SENTENCE_RECONSTRUCTION" },
  G_Others_026: { title: "AI 시스템 사고에 따른 인명 피해", category: "TERMINOLOGY_AND_SYNTAX" },
  A_SYS_AUTH_012: { title: "모바일 앱에서의 자율 행동에 따른 피해", category: "TERMINOLOGY_AND_SYNTAX" },
  A_SYS_SELFCOR_001: { title: "에이전트 자기 수정의 신뢰성 문제", category: "TERMINOLOGY_AND_SYNTAX" },
  G_INT_WEAP_001: { title: "폭력과 무력 충돌", description: "AI 시스템이 사이버 공격·보안 침해 또는 치명적 생물무기·화학무기의 개발을 선동·촉진하거나 실행을 지원하여 폭력이나 무력 충돌을 초래하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_INT_WEAP_009: { title: "CBRN 정보 획득·무기 설계 역량 개발 장벽 저하", description: "AI 시스템이 화학·생물·방사능·핵무기 또는 기타 위험 물질·작용제와 관련된 실행 가능한 정보의 획득·합성이나 설계 역량 개발의 장벽을 낮추는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  G_INT_REPR_020: { description: "대화형 AI 에이전트가 언어 속 정체성 표지나 성별화된 제품명 등 설계 요소를 통해 비서 역할을 특정 성별 또는 민족 정체성과 본질적으로 결부시켜 유해한 고정관념을 영속시키는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  P_SYS_HARDWARE_002: { title: "하드웨어 결함에 따른 의도하지 않은 동작 변화", description: "잠재된 제조 결함 또는 우주선(cosmic ray)에 의한 비트 반전과 같은 배포 후 환경 영향이 로봇·휴머노이드 또는 피지컬 AI 시스템의 내부 상태를 변경하여 의도하지 않은 동작 변화를 유발하는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  A_SYS_AUTH_015: { description: "AI 에이전트가 과업 수행을 위해 하위 에이전트를 생성할 때 하위 에이전트의 수명 주기가 상위 에이전트와 분리되어, 상위 에이전트가 종료된 뒤에도 하위 에이전트가 계속 작동하고 재귀적으로 추가 하위 에이전트를 생성함으로써 에이전트 수와 자원 사용량이 통제되지 않은 채 증가하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_INT_REPR_001: { description: "AI 시스템의 복잡하고 비전통적인 자동 표상·분류 방식이 논바이너리인 사람을 자신이 속하지 않은 성별 범주로 분류하는 등 개인의 자율성과 자신의 정체성을 스스로의 방식으로 밝힐 능력을 약화시키는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_INT_WEAP_016: { description: "AI 시스템이 무기화 전략의 수립과 전술적 활용을 지원하여 대규모 물리적·사이버 위해의 실행 가능성을 높이는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_INT_WEAP_017: { description: "AI 모델이 기존 무기 체계에 접근하거나 새로운 무기 제작에 기여하여, 생물무기를 조립하거나 실행 가능한 지침을 제공하고 새로운 무기의 개발로 이어지는 과학적 발견을 돕는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_INT_WEAP_019: { description: "AI 시스템이 무기의 개발·제조·획득·확산·운용과 그 은닉을 지원하여 대규모 물리적·사이버 위해의 실행 가능성을 높이는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_SOC_ECON_009: { description: "AI 기술로 인한 일자리 부족과 불공정한 알고리즘, 허위정보, 그리고 AI 시스템에 의해 유발되거나 증폭된 사회적 지위 및 부의 격차 확대가 지역사회의 복지와 결속을 훼손하는 리스크. 이러한 문제로 인한 파업과 시위를 비롯한 시민 불안이 확산되어 사회 전반의 안정이 흔들릴 수 있는 위험.", category: "SENTENCE_RECONSTRUCTION" },
  G_SOC_GOV_011: { description: "생성형 AI의 새로운 위험에 대응할 법적 규제, 국제 공조, 프런티어 모델에 대한 구속력 있는 안전 기준과 제재 메커니즘이 부재하여 관련 위험을 적절히 관리하지 못하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_SOC_GOV_020: { description: "AI에 대한 반복적 위임으로 실질적 의사결정 권한과 결정의 소유권이 명시적 거버넌스 결정 없이 특정 가능한 인간 행위자로부터 이전되고, 업무 흐름이 위임에 의존하게 되면서 권한을 인간 의사결정자에게 되돌리는 데 과도한 비용이 들거나 사실상 불가능해지는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_INT_PRIV_004: { title: "사생활·평판 정보 노출", description: "AI 시스템이 개인의 사생활 또는 평판에 관한 정보를 노출하는 콘텐츠를 생성하거나, 그러한 정보 노출로 이어지는 판단·행동을 수행·조장·지원하여 프라이버시와 정보자기결정권을 침해하는 리스크.", category: "TERMINOLOGY_AND_SYNTAX" },
  G_SYS_EVAL_015: { title: "상황 인식에 따른 평가 기만", description: "AI 시스템이 자신의 훈련·평가·배포 상태를 식별하는 상황 인식을 이용해 평가 중에 의도적으로 안전한 것처럼 행동하거나 위험 역량·목표를 은폐하여 평가의 타당성을 훼손하고 잘못된 안전성 확신을 초래하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  P_SYS_CONTROL_006: { title: "물리적 운용 환경의 분포 이동", description: "건물·도로·공장·가정·병원 또는 기상 조건 등 물리적 운용 환경이 로봇·휴머노이드 또는 피지컬 AI 시스템의 제어 정책이 탐지·적응할 수 있는 속도보다 빠르게 변화하여 경로 계획·동작 제어·구동이 부정확해지고 안전하지 않은 물리적 행동을 유발하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  P_SYS_CONTROL_033: { title: "부실하게 설계된 피지컬 AI 제어 시스템에 의한 상해", description: "로봇·휴머노이드 또는 피지컬 AI 제어 시스템의 설계 결함이 안전하지 않은 물리적 행동을 유발하여 심리적 고통, 신체 상해 또는 그 밖의 물리적 피해를 초래하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  P_SYS_CONTROL_040: { title: "안전 제약 적용 지연", category: "TERMINOLOGY_AND_SYNTAX" },
  P_SYS_STATE_001: { title: "물리 상태 추정 데이터의 합성-실세계 괴리", description: "로봇·휴머노이드 또는 피지컬 AI 시스템의 물리 상태 추정·센서 융합 모델에 사용된 합성·시뮬레이션 학습 데이터가 실제 센서 잡음, 접촉, 힘, 운동 및 환경 변화를 충분히 반영하지 못하여 부정확한 내부 상태 추정과 안전하지 않은 물리적 행동을 초래하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  P_SYS_STATE_003: { title: "접촉 집약적 조작에서의 힘 감지 실패", description: "로봇의 접촉 집약적 조작 정책이 힘·촉각·음향·시각 단서를 올바르게 활용하지 못하여 과도한 접촉 압력·충격이나 물체 손상을 유발하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_Others_117: { title: "데이터 수집 관련 법적 제한 우회에 따른 규제 위반", category: "TERMINOLOGY_AND_SYNTAX" },
  A_SYS_AUTH_011: { title: "자율 사이버 공격을 통한 인간 통제력 약화", category: "TERMINOLOGY_AND_SYNTAX" },
  G_Others_047: { description: "인간 언어의 모호성으로 인해 AI 시스템 또는 AI 알고리즘과의 프롬프트 기반 상호작용에서 오류나 오해가 발생하고 프롬프트 디버깅이 어려워져, 이용자가 유용한 산출물을 얻지 못하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  P_Others_002: { description: "로봇·휴머노이드 또는 피지컬 AI 시스템의 배포 전 설계 단계에서 발생한 코드 결함, 목적 함수 가중치 불균형, 인간 가치와 어긋난 목표 설정 등으로 인해 시스템 행동이 의도된 형식적 속성에서 이탈하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  P_INT_SAFETY_016: { description: "가정용 로봇·휴머노이드 또는 피지컬 AI 시스템의 벤치마크가 특정 생활 공간·일과·가전제품·취약 사용자와의 상호작용을 누락하여 배포 위험이 시험되지 않은 채 남는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  P_INT_SAFETY_017: { description: "가정용 로봇·휴머노이드 또는 피지컬 AI 시스템의 벤치마크가 물체·배치·인간 행동·위험 요소를 개별적으로는 포함하지만 이들의 희귀한 조합을 누락하여 배포 위험을 충분히 평가하지 못하는 위험.", category: "SENTENCE_RECONSTRUCTION" },
  P_SYS_CONTROL_044: { title: "물리적 위해 완화 책임 미지정", description: "로봇·휴머노이드 또는 피지컬 AI 시스템의 배포 전후 물리적 위해를 식별·완화할 책임 주체가 지정되지 않아 충돌·압착·낙하·과도한 힘·위험 구역 침범을 방지하는 안전 제어가 누락되거나 지연되는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  G_Others_143: { description: "로봇·휴머노이드 또는 피지컬 AI 시스템을 통한 자동화가 수작업·물류·서비스·돌봄·검사·보안·유지보수 업무를 해당 노동자가 재교육이나 대체 일자리로 전환할 수 있는 속도보다 빠르게 대체하여 고용 불안과 생계 피해를 초래하는 위험.", category: "SENTENCE_RECONSTRUCTION" },
  P_INT_SAFETY_005: { description: "멀티모달·체화형 AI 시스템이 텍스트·이미지·영상·센서 입력에 이미 나타난 위험 상태를 식별하지 못하거나 진행 중인 움직임·접촉·환경 변화가 곧 위험을 초래할 것을 예측하지 못한 채 행동을 선택하여 충돌·손상·상해를 초래하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  P_INT_SAFETY_008: { description: "체화형 AI 에이전트가 물리적 위험을 수반하는 지시가 명시적으로 제시되었거나 일반적인 과업 요청에 암묵적으로 포함된 경우에도 이를 식별·거부하지 못하고 안전하지 않은 행동을 수행하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  P_INT_SAFETY_014: { title: "헌법 기반 안전 규칙 집행 실패", description: "로봇·휴머노이드 또는 피지컬 AI 시스템의 헌법 기반 안전 계층이 지시·시각적 맥락·과업 프레이밍이 명시된 물리적 안전 규칙과 충돌할 때 해당 규칙을 적용하지 못하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  P_INT_TAMPER_003: { description: "체화형 AI 에이전트가 신체 위해·침입·절도·사기·파괴·도피 또는 그 밖의 불법적인 물리적 행위를 요구하는 사용자 요청을 수용·실행하거나 실질적으로 지원하여 사람이나 재산에 피해를 초래하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  P_INT_TAMPER_005: { description: "공격자가 유해한 물리적 행동 지시를 무해하거나 정상적인 과업 요청으로 위장하여 체화형 AI 에이전트가 이를 수용·실행하도록 유도하는 위험.", category: "SENTENCE_RECONSTRUCTION" },
  P_SYS_CONTROL_007: { description: "로봇·휴머노이드 또는 피지컬 AI 시스템이 사람·차량·도구·물체가 예기치 않게 경로에 진입하는 경우를 포함한 위험한 물리적 상황에서 적시에 개입하거나 위험 행동을 거부하거나 이동 계획을 수정하지 못하여 충돌이나 상해를 초래하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  P_SYS_CONTROL_018: { description: "자동 주행 AI 시스템이 인지·계획·소프트웨어 결함이나 엣지 케이스로 안전하지 않은 제어 결정을 내리거나, 시간이 촉박한 상황에서 제어권을 모호하게 또는 뒤늦게 전환하여 인간과 시스템 어느 쪽도 필요한 안전 조치를 수행하지 못하게 함으로써 충돌 위험을 초래하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  P_SYS_CONTROL_029: { description: "로봇·휴머노이드 또는 피지컬 AI 시스템이 그리퍼의 형상·유형 또는 실제 접촉 역학이 부과하는 물리적 제약을 위반하는 행동을 선택하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  P_SYS_CONTROL_052: { description: "로봇·휴머노이드 또는 피지컬 AI 시스템의 플래너가 형식적으로는 실행 가능하지만 주변 사람·취약 물체·교통 참여자 또는 제약된 작업 공간에 안전하지 않은 궤적을 생성하는 위험.", category: "SENTENCE_RECONSTRUCTION" },
  P_SYS_CONTROL_055: { description: "시뮬레이션에서 실제 하드웨어로 직접 전이된 로봇 보행 제어기가 접촉·순응성·마찰·외란 동역학의 차이에 적응하지 못해 불안정해지고 전도·충돌 또는 제어 상실을 초래하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  P_SYS_STATE_007: { description: "로봇·휴머노이드 또는 피지컬 AI 시스템의 GPS·SLAM·관성 감지·지도 정렬 오차가 누적되어 시스템이 잘못된 자기 위치 추정에 기반해 행동하는 위험.", category: "SENTENCE_RECONSTRUCTION" },
  P_SYS_STATE_009: { description: "로봇·휴머노이드 또는 피지컬 AI 시스템에서 카메라·라이다·레이더·촉각·고유수용성 감각 신호가 상충하여 불안정한 장면 추정과 안전하지 않은 후속 제어 결정을 초래하는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
  P_Others_005: { description: "로봇·휴머노이드 또는 피지컬 AI 시스템의 런타임 안전 모니터가 속도·힘·이격 거리·작업 공간·충돌·물체 사용·과업 프로토콜에 관한 제약을 감지하거나 집행하지 못하여 위해가 발생할 때까지 안전하지 않은 동작이 지속되는 리스크.", category: "SENTENCE_RECONSTRUCTION" },
};

function rowObject(header, values) {
  return Object.fromEntries(header.map((field, index) => [String(field).replace(/^\uFEFF/, ""), String(values[index] ?? "")]));
}
function tokens(value) {
  return [...new Set(String(value ?? "").replaceAll("|", ";").replaceAll(",", ";").split(";").map((part) => part.trim()).filter(Boolean))].sort();
}
function beforeHash(row) {
  const canonical = [
    tokens(row.source_row_id).join("|"), tokens(row.Source_L4_IDs).join("|"), row.L3_ID,
    row.L4_Title_en, row.L4_Title_ko, row.L4_Description_ko,
  ].join("\u001f");
  return createHash("sha256").update(canonical, "utf8").digest("hex");
}
function mechanicalEdit(value) {
  let result = String(value ?? "").normalize("NFC");
  for (const [before, after] of replacements) result = result.replaceAll(before, after);
  return result.replace(/[ \t]+/g, " ").trim();
}

const cards = [];
for (const domain of domains) {
  const csvUrl = new URL(`../05_human_review_round2/archive/pre_korean_copyedit_clean_800_20260829/L4_${domain}_Human_Review_Round2_Applied.csv`, import.meta.url);
  const workbook = await Workbook.fromCSV(await fs.readFile(csvUrl, "utf8"), { sheetName: domain });
  const values = workbook.worksheets.getItem(domain).getUsedRange().values;
  const header = values[0].map((value) => String(value).replace(/^\uFEFF/, ""));
  for (const required of requiredFields) {
    if (!header.includes(required)) throw new Error(`Missing ${required} in ${domain}`);
  }
  for (const valuesRow of values.slice(1)) cards.push({ domain, ...rowObject(header, valuesRow) });
}

const wordingOwnedByUserOperation = new Set(["G_INT_WEAP_002", "P_SYS_STATE_002"]);
const observedManualIds = new Set();
const manifestRows = [];
for (const card of cards) {
  if (wordingOwnedByUserOperation.has(card.L4_ID)) continue;
  const manual = manualEdits[card.L4_ID];
  let titleAfter = mechanicalEdit(card.L4_Title_ko);
  let descriptionAfter = mechanicalEdit(card.L4_Description_ko);
  if (manual) {
    observedManualIds.add(card.L4_ID);
    if (manual.title) titleAfter = mechanicalEdit(manual.title);
    if (manual.description) descriptionAfter = mechanicalEdit(manual.description);
  }
  if (titleAfter === card.L4_Title_ko && descriptionAfter === card.L4_Description_ko) continue;
  const changedFields = [];
  if (titleAfter !== card.L4_Title_ko) changedFields.push("L4_Title_ko");
  if (descriptionAfter !== card.L4_Description_ko) changedFields.push("L4_Description_ko");
  const category = manual?.category ?? (card.L4_Description_ko.startsWith(replacements[0][0]) ? "GRAMMAR_AND_ORTHOGRAPHY" : "ORTHOGRAPHY");
  manifestRows.push([
    "",
    "KOREAN_COPYEDIT_20260829",
    card.domain,
    card.L4_ID,
    tokens(card.source_row_id).join("; "),
    tokens(card.Source_L4_IDs).join("; "),
    card.L3_ID,
    card.L4_Title_en,
    card.L4_Title_ko,
    card.L4_Description_ko,
    titleAfter,
    descriptionAfter,
    changedFields.join("; "),
    beforeHash(card),
    category,
    category === "ORTHOGRAPHY" || category === "GRAMMAR_AND_ORTHOGRAPHY" ? "L3_MASTER|KOREAN_ORTHOGRAPHY_AND_SPACING_QA" : "L3_MASTER|SOURCE_ENGLISH_DEFINITION|POLICY_AND_TECHNICAL_TERMINOLOGY_QA",
    category === "SENTENCE_RECONSTRUCTION" || category === "TERMINOLOGY_AND_SYNTAX" ? "YES" : "NO",
    "APPROVED_LANGUAGE_QA_20260829",
  ]);
}

const missingManualIds = Object.keys(manualEdits).filter((id) => !observedManualIds.has(id));
if (missingManualIds.length) throw new Error(`Manual edit IDs not found: ${missingManualIds.join(", ")}`);
manifestRows.forEach((row, index) => { row[0] = `KOC-${String(index + 1).padStart(4, "0")}`; });

const header = [
  "Decision_ID", "Approval_Batch_ID", "Domain", "Observed_L4_ID_PreApply", "Source_Row_IDs",
  "Source_L4_IDs_Before", "Target_L3_ID", "Expected_Title_en", "Expected_Title_ko_Before",
  "Expected_Description_ko_Before", "Approved_Title_ko_After", "Approved_Description_ko_After",
  "Allowed_Changed_Fields", "Expected_Before_SHA256", "Editorial_Category", "Terminology_Evidence",
  "Clear_Mapping_Evidence", "Approval_Status",
];
const workbook = await Workbook.create();
const sheet = workbook.worksheets.add("Copyedit");
const values = [header, ...manifestRows];
sheet.getRangeByIndexes(0, 0, values.length, header.length).values = values;
const inspection = await workbook.inspect({
  kind: "table",
  range: `Copyedit!A1:R${Math.min(values.length, 16)}`,
  include: "values",
  tableMaxRows: 16,
  tableMaxCols: header.length,
  tableMaxCellChars: 100,
  maxChars: 12000,
});
console.log(inspection.ndjson);
console.log(JSON.stringify({ manifest_rows: manifestRows.length, manual_rows: observedManualIds.size }));

function csvCell(value) {
  const text = String(value ?? "");
  return /[",\r\n]/.test(text) ? `"${text.replaceAll('"', '""')}"` : text;
}
const csv = values.map((row) => row.map(csvCell).join(",")).join("\n") + "\n";
await fs.writeFile(outputPath, csv, "utf8");
